[tool.poetry]
name = "geo"
version = "0.1.0"
description = ""
authors = ["Artem <artctvcode@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
openpyxl = "^3.0.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
