
def calculate(lon_1: float, lat_1: float, lon_2: float, lat_2: float) -> float:
    ...

def combinations(queue_values: list[float], elemts_values: list[float], elemts_size: int) -> list[float]:
    ...
